node {
    stage 'build'
        echo 'Building....'
        sh 'git add .'
        sh 'git stash'
        sh 'git checkout qa'
        sh 'git pull'
        sh 'git fetch upstream'
    stage 'test'
        echo 'Testing....'
    stage 'deploy'
        echo 'Deploying....'
        sh 'git push upstream --delete golden'
        sh 'git checkout golden'
        sh 'git add .'
        //sh 'git commit -a -m "Merging Version"'
        sh 'git push upstream golden'
}
