node {
    stage 'build'
        echo 'Building....'
        sh 'git add .'
        sh 'git stash'
        sh 'git pull'
        sh 'git fetch upstream'
    stage 'test'
        echo 'Testing....'
    stage 'deploy'
        echo 'Deploying....'
        sh 'git push upstream --delete golden'
        sh 'git checkout qa'
        sh 'git branch -d golden'
        sh 'git checkout -b golden'
        sh 'git add .'
        sh 'git commit -a -m "Merging Version"'
}
