node {
    stage 'build'
        echo 'Building....'
        sh 'rm -rf ./*'
        sh 'rm -rf ./.*'
        sh 'git clone https://github.com/jpohlmann/pipelinetest/ ./'
        sh 'git remote add upstream https://github.com/jpohlmann/pipelineprod/'
        sh 'git add .'
        sh 'git stash'
        sh 'git checkout qa'
        sh 'git pull'
        sh 'git fetch upstream'
    stage 'test'
        echo 'Testing....'
    stage 'deploy'
        echo 'Deploying....'
        sh 'git checkout upstream/golden'
        sh 'git branch ugolden'
        sh 'git checkout ugolden'
        sh 'git merge qa -Xours'
        sh 'git add .'
        //Deploy scripts here
        sh 'git commit -m "Merging for deployment" || true'
        sh 'git push upstream ugolden:golden'
        sh 'git checkout qa'
        sh 'git branch ugolden -D'
}
